config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'landing#index'

  resources :users do 
    resources :books, only: :index
  end

  resources :books, except: :index

end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :user

  def range(short=true)
    print_string = short ? ('%b %d, %Y') : ('%B %d, %Y')
    [started, ended].compact.map{ |d| d.strftime( print_string ) }.join("<em> to </em>")
  end

  def full_name
    ["<b>#{name}</b>", "<em> #{author} </em>"].compact.join(" by ")
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :books

  def name
    [first, last].reject(&:blank?).join(" ")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    [:first, :last].each do |field|
      [:sign_up, :account_update].each do |scenario|
        devise_parameter_sanitizer.for(scenario) << field
      end
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :load_user, only: [:index, :create, :new]
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @books = @user.books.order(ended: :desc, started: :desc).all
  end

  def show
  end

  def new
    @book = @user.books.new
  end

  def edit
  end

  def create
    @book = @user.books.new(book_params)
    @book.started = Time.now
    
    if @book.save
      redirect_to @book
    else
      render :new
    end
  end

  def update
    if @book.update(book_params)
      redirect_to @book
    else
      render :edit
    end
  end

  def destroy
    @book.destroy
    redirect_to books_url
  end

  private

  def load_user
    @user = User.find_by( id: params[:user_id] ) || current_user
  end

  def set_book
    @book = Book.find(params[:id])
    if @book.user == current_user
      @user = current_user
    else
      redirect_to root_path
    end
  end

  def book_params
    params.require(:book).permit(:name, :author, :started, :ended, :rating, :summary, :thoughts, :user_id)
  end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController

  layout false

  def index
    redirect_to user_books_path( current_user ) if current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def md(text)
    Redcarpet::Markdown.new(Redcarpet::Render::HTML, { tables: true }).render(text).html_safe
  end

  def stars(book)
    return '' unless book.rating
    string = ''
    book.rating.times{ string += "<div class='glyphicon glyphicon-star'></div>" }
    ( 5 - book.rating ).times{ string += "<div class='glyphicon glyphicon-star-empty'></div>" }
    string.html_safe
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.haml
= form_for @book, html: { class: "form-horizontal", role: "form" } do |f|
  -if @book.errors.any?
    .alert.alert-danger.alert-dismissable{role: "alert"}
      %button.close{type: "button", data: {dismiss: "alert"} }
        %span{aria: {hidden: "true"} } &times;
        %span.sr-only Close
      %h4= "#{pluralize(@book.errors.count, "error")} prohibited this book from being saved:"

      %ul
        - @book.errors.full_messages.each do |msg|
          %li= msg
  .form-contents
    .form-group
      = f.text_field :name, class: 'form-control', placeholder: 'Name'
    .form-group
      = f.text_field :author, class: 'form-control', placeholder: 'Author'
    .form-group
      = f.date_select :started, class: 'form-control'
    .form-group
      = f.select :rating, options_for_select( (0..5).to_a ), class: 'form-control'
    .form-group
      = f.text_area :summary, class: 'form-control', placeholder: 'Summary'
    .form-group
      = f.text_area :thoughts, class: 'form-control thoughts', placeholder: 'Thoughts (accepts Markdown)'
    .form-group
      = f.submit "Save Book", class: 'btn btn-primary'

app/views/books/edit.html.haml
= form_for @book, html: { class: "form-horizontal finish", role: "form" } do |f|
  -if @book.errors.any?
    .alert.alert-danger.alert-dismissable{role: "alert"}
      %button.close{type: "button", data: {dismiss: "alert"} }
        %span{aria: {hidden: "true"} } &times;
        %span.sr-only Close
      %h4= "#{pluralize(@book.errors.count, "error")} prohibited this book from being saved:"

      %ul
        - @book.errors.full_messages.each do |msg|
          %li= msg
  .form-contents
    .form-group
      = f.text_field :name, class: 'form-control', placeholder: 'Name'
    .form-group
      = f.text_field :author, class: 'form-control', placeholder: 'Author'
    .form-group
      = f.date_select :ended, class: 'form-control'
    .form-group
      = f.select :rating, options_for_select( (0..5).to_a ), class: 'form-control'
    .form-group
      = f.text_area :summary, class: 'form-control', placeholder: 'Summary'
    .form-group
      = f.text_area :thoughts, class: 'form-control thoughts', placeholder: 'Thoughts (accepts Markdown)'
    .form-group{ style: 'text-align: center' }
      = f.submit "Save Book", class: 'btn btn-primary'

app/views/books/index.html.haml
.table-responsive
  %table.table
    %thead
      %tr
        %th Name
        %th Read
        %th Stars
        %th Summary
        %th Thoughts
        - if @books.count > 0
          %th
          %th

    %tbody
      - @books.each_with_index do |book, index|
        %tr{ class: (index.odd? ? 'odd' : 'even') }
          %td= link_to book.full_name.html_safe, book
          %td= book.range.html_safe
          %td= stars( book )
          %td= book.summary.to_s.truncate(15)
          %td= book.thoughts.to_s.truncate(15)
          %td
            = link_to edit_book_path(book) do
              .glyphicon.glyphicon-check
          %td
            = link_to book, data: { confirm: 'Are you sure?' }, method: :delete do
              .glyphicon.glyphicon-trash
  .container{ style: 'text-align: center' }
    = link_to new_book_path, class: 'btn btn-primary' do
      %span.glyphicon.glyphicon-plus
      Add Book

app/views/books/new.html.haml
= form_for @book, html: { class: "form-horizontal new", role: "form" } do |f|
  -if @book.errors.any?
    .alert.alert-danger.alert-dismissable{role: "alert"}
      %button.close{type: "button", data: {dismiss: "alert"} }
        %span{aria: {hidden: "true"} } &times;
        %span.sr-only Close
      %h4= "#{pluralize(@book.errors.count, "error")} prohibited this book from being saved:"

      %ul
        - @book.errors.full_messages.each do |msg|
          %li= msg
  .form-contents
    .form-group
      = f.text_field :name, class: 'form-control', placeholder: 'Name'
    .form-group
      = f.text_field :author, class: 'form-control', placeholder: 'Author'
    .form-group{ style: 'text-align: center' }
      = f.submit "Save Book", class: 'btn btn-primary'

app/views/books/show.html.haml
.container.book-show

  .links
    = link_to user_books_path(current_user), class: 'btn btn-default' do
      %span.glyphicon.glyphicon-list-alt
      Back
    = link_to edit_book_path(@book), class: 'btn btn-primary' do
      %span.glyphicon.glyphicon-pencil
      Edit

  .inner-container
    .show-title= @book.full_name.html_safe

    %h4= "(#{ @book.range(false) })".html_safe

    %h3= stars( @book )

    %br

    %h4= "“#{ @book.summary }”"

  .container.thoughts-container
    %p= md( @book.thoughts || '' )

app/views/landing/index.html.haml
!!!
%html
  %head
    %meta{charset: "utf-8"}
    %meta{content: "IE=edge", "http-equiv" => "X-UA-Compatible"}
    %meta{content: "width=device-width, initial-scale=1", name: "viewport"}
    %meta{content: "", name: "description"}
    %meta{content: "", name: "author"}
    %title BookTrail

    = javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js"

    = stylesheet_link_tag    'landing', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  
  %body
    .landing-page
      .landing-cover
        .text-area
          %h1.centered-header BookTrail
          %h2.centered-subtitle Leave no book behind
          %ul
            %li.button-link= link_to 'Sign In', new_user_session_path, class: 'btn-primary'
            %li.button-link= link_to 'Sign Up', new_user_registration_path, class: 'btn-primary'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{charset: "utf-8"}
    %meta{content: "IE=edge", "http-equiv" => "X-UA-Compatible"}
    %meta{content: "width=device-width, initial-scale=1", name: "viewport"}
    %meta{content: "", name: "description"}
    %meta{content: "", name: "author"}
    %title BookTrail

    = javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js"

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  %body
    .body-overlay
      %nav.navbar.navbar-inverse.navbar-fixed-top{role: "navigation"}
        .container
          .navbar-header
            %button.navbar-toggle.collapsed{type: "button", data: {toggle: "collapse", target: "#navbar"}, aria: {expanded: "false", controls: "navbar"} }
              %span.sr-only Toggle navigation
              %span.icon-bar
              %span.icon-bar
              %span.icon-bar
            = link_to "BookTrail", root_path, class: "navbar-brand"
          #navbar.collapse.navbar-collapse
            %ul.nav.navbar-nav
              - if current_user
                %li= link_to 'Books', user_books_path(current_user)
            %ul.nav.navbar-nav.pull-right
              - if current_user
                %li= link_to 'Profile', edit_user_registration_path
                %li= link_to 'Sign Out', destroy_user_session_path, method: :delete
              - else
                %li= link_to 'Sign In', new_user_session_path
                %li= link_to 'Sign Up', new_user_registration_path



      .container
        - flash.each do |name, msg|
          = content_tag :div, class: "alert alert-#{name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do
            %button.close{type: "button", data: {dismiss: "alert"} }
              %span{aria: {hidden: "true"} } &times;
              %span.sr-only Close
            = msg
        = yield